#!/usr/bin/env python

import sys, re

s = sys.argv[1]

p = re.compile(r"//.*?$|/\*.*?\*/", re.MULTILINE | re.DOTALL)
s = p.sub("", s)

for thing in re.findall(r"[A-Za-z_]\w*", s):
    print("case %s:" % thing)

