#!/usr/bin/env python

import os, sys
import hashlib

def list_all(path):
    for item in os.listdir(path):
        item_path = os.path.join(path, item)
        if os.path.isdir(item_path):
            for thing in list_all(item_path):
                yield thing
        else:
            yield item_path 

myName, workingFolder, outFile = sys.argv

out = open(outFile, "w")
original = os.getcwd()
os.chdir(workingFolder)
for file in list_all(".."):
    m = hashlib.md5()
    m.update(open(file, "rb").read())
    out.write("%s %s\n" % (m.hexdigest(), file))

out.close()
os.chdir(original)
